services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: Library_Management_System
      MYSQL_USER: library_app
      MYSQL_PASSWORD: library_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      API_PORT: 5050
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: library_app
      DB_PASSWORD: library_pass
      DB_NAME: Library_Management_System
      FRONTEND_ORIGINS: http://localhost:8080,http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:5050"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_API_BASE_URL: ""
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  db_data:
